
GCC = gcc
CFLAGS = -Wall -Wextra -Werror -std=c11 -pedantic -O2
CXX = g++
CXXFLAGS = -Wall -Wextra -Werror -std=c++20 -pedantic -O2

.PHONY: all clean

all: day1 day1_plus

day1: day1.c

day1_plus: day1_plus.cpp

clean:
	rm -f day1 day1_plus
